# Generated by Django 4.0.5 on 2023-06-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='create_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='orders',
            name='pay_info',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='poduct',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
