# Generated by Django 4.0.5 on 2023-06-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_orders_create_date_alter_orders_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='poduct',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='orders',
            name='ready_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
