# Generated by Django 4.0.5 on 2023-08-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_rename_poduct_orders_product_alter_orders_ready_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='orders'),
        ),
    ]
