# Generated by Django 4.0.5 on 2023-08-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_orders_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='comment',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='orders',
            name='delivery',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
