# Generated by Django 4.0.5 on 2023-08-01 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_orders_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='comment',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='orders/'),
        ),
    ]
