# Generated by Django 4.0.5 on 2023-08-04 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_orders_comment_alter_orders_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='clients',
            name='name',
            field=models.CharField(blank=True, default='anon', max_length=50),
        ),
        migrations.AlterField(
            model_name='clients',
            name='tel',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='orders',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.clients'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='comment',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='orders',
            name='file',
            field=models.FileField(blank=True, upload_to='orders/'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='product',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='ready_date',
            field=models.DateField(blank=True),
        ),
    ]
