# Generated by Django 4.0.5 on 2023-08-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_clients_email_alter_clients_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='pay_info',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
