# Generated by Django 4.0.5 on 2023-07-19 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=20)),
                ('cost_per_m', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Wide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wide_size', models.FloatField()),
                ('heigth_size', models.FloatField()),
                ('post_obr', models.CharField(choices=[('0', 'Без обработки'), ('1', 'Проклейка периметра'), ('2', 'Люверсы по углам'), ('3', 'Люверсы каждые 30см'), ('4', 'Люверсы каждые 50см')], max_length=30)),
                ('cost', models.IntegerField()),
                ('material_print', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='wide.material')),
            ],
        ),
    ]
