# Generated by Django 4.0.5 on 2023-07-26 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wide', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_obr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_wide_production', models.CharField(max_length=30)),
                ('title_post_obr', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='material',
            name='material',
            field=models.CharField(max_length=30),
        ),
        migrations.RemoveField(
            model_name='wide',
            name='post_obr',
        ),
        migrations.AddField(
            model_name='wide',
            name='post_obr',
            field=models.ManyToManyField(to='wide.post_obr'),
        ),
    ]
