# Generated by Django 4.0.5 on 2023-07-26 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wide', '0002_post_obr_alter_material_material_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wide',
            name='post_obr',
        ),
        migrations.AddField(
            model_name='wide',
            name='post_obr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wide.post_obr'),
        ),
    ]
