# Generated by Django 4.0.5 on 2023-07-26 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wide', '0003_remove_wide_post_obr_wide_post_obr'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='type_material',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
