# Generated by Django 4.0.5 on 2023-07-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wide', '0004_material_type_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='wide',
            name='type_production',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
