# Generated by Django 4.0.5 on 2023-08-05 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wide', '0005_wide_type_production'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='type_material',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='wide',
            name='heigth_size',
            field=models.FloatField(max_length=5),
        ),
        migrations.AlterField(
            model_name='wide',
            name='material_print',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wide.material'),
        ),
        migrations.AlterField(
            model_name='wide',
            name='post_obr',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='wide.post_obr'),
        ),
        migrations.AlterField(
            model_name='wide',
            name='type_production',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='wide',
            name='wide_size',
            field=models.FloatField(max_length=5),
        ),
    ]
