# Generated by Django 4.0.5 on 2023-06-21 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format_paper', models.CharField(max_length=20)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Poly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper', models.CharField(choices=[('130', '130 г/м'), ('170', '170 г/м'), ('300', '300 г/м')], max_length=20)),
                ('pressrun', models.IntegerField()),
                ('duplex', models.BooleanField()),
                ('post_obr', models.JSONField()),
                ('cost', models.IntegerField()),
                ('format_p', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='poly.formats')),
            ],
        ),
    ]
