# Generated by Django 4.0.5 on 2023-06-13 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formats_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format_paper', models.CharField(max_length=20)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, null=True)),
                ('type_production', models.CharField(max_length=20, null=True)),
                ('production', models.CharField(max_length=100, null=True)),
                ('time_ready', models.DateTimeField(null=True)),
                ('cost', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Leaflets_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper', models.CharField(choices=[('130', '130 г/м'), ('170', '170 г/м'), ('300', '300 г/м')], default='130', max_length=20)),
                ('pressrun', models.IntegerField()),
                ('duplex', models.BooleanField(choices=[(True, 'Двухсторонняя печать'), (False, 'Односторонняя печать')], default=True)),
                ('cost', models.IntegerField(null=True)),
                ('format', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='poly.formats_model')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Card_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper', models.CharField(choices=[('130', '130 г/м'), ('170', '170 г/м'), ('300', '300 г/м')], default='130', max_length=20)),
                ('pressrun', models.IntegerField()),
                ('duplex', models.BooleanField(choices=[(True, 'Двухсторонняя печать'), (False, 'Односторонняя печать')], default=True)),
                ('cost', models.IntegerField(null=True)),
                ('format', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='poly.formats_model')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
