# Generated by Django 4.0.5 on 2023-06-13 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poly', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booklet_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper', models.CharField(choices=[('130', '130 г/м'), ('170', '170 г/м'), ('300', '300 г/м')], default='130', max_length=20)),
                ('pressrun', models.IntegerField()),
                ('duplex', models.BooleanField(choices=[(True, 'Двухсторонняя печать'), (False, 'Односторонняя печать')], default=True)),
                ('cost', models.IntegerField(null=True)),
                ('format', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='poly.formats_model')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
