# Generated by Django 4.0.5 on 2023-06-21 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poly', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formats',
            old_name='format_paper',
            new_name='format_p',
        ),
    ]
