# Generated by Django 4.0.5 on 2023-05-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poly', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper', models.CharField(help_text='Плотность бумаги', max_length=20)),
                ('pressrun', models.IntegerField(help_text='Тираж')),
                ('duplex', models.BooleanField(choices=[(True, '4+4'), (False, '4+0')], default=True, help_text='Дуплекс')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
