# Generated by Django 4.0.5 on 2023-05-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poly', '0002_cards_delete_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='x',
            field=models.IntegerField(default=90, help_text='Горизонтальный размер'),
        ),
        migrations.AddField(
            model_name='cards',
            name='y',
            field=models.IntegerField(default=50, help_text='Вертикальный размер'),
        ),
    ]
