# Generated by Django 4.0.5 on 2023-06-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poly', '0002_rename_format_paper_formats_format_p'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poly',
            name='duplex',
            field=models.CharField(choices=[(True, 'Двухсторонняя печать'), (False, 'Односторонняя печать')], max_length=50),
        ),
    ]
