# Generated by Django 4.0.5 on 2023-06-13 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poly', '0002_booklet_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_model',
            name='time_ready',
        ),
    ]
