# Generated by Django 4.0.5 on 2023-06-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poly', '0003_remove_order_model_time_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_model',
            name='time_ready',
            field=models.DateTimeField(null=True),
        ),
    ]
