# Generated by Django 4.0.5 on 2023-05-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poly', '0003_cards_x_cards_y'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='paper',
            field=models.CharField(choices=[(130, '130 г/м'), (170, '170 г/м'), (300, '300 г/м')], help_text='Плотность бумаги', max_length=20),
        ),
    ]
