# Generated by Django 4.0.5 on 2023-06-21 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poly', '0004_alter_poly_post_obr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poly',
            name='duplex',
            field=models.BooleanField(choices=[(True, 'Двухсторонняя печать'), (False, 'Односторонняя печать')], max_length=50),
        ),
    ]
