# Generated by Django 4.0.5 on 2023-06-13 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poly', '0004_order_model_time_ready'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_model',
            name='cost',
        ),
    ]
