# Generated by Django 4.0.5 on 2023-05-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poly', '0004_alter_cards_paper'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='cost',
            field=models.IntegerField(help_text='Цена', null=True),
        ),
        migrations.AlterField(
            model_name='cards',
            name='paper',
            field=models.CharField(choices=[('300', '300 г/м')], help_text='Плотность бумаги', max_length=20),
        ),
    ]
