# Generated by Django 4.0.5 on 2023-05-30 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poly', '0005_cards_cost_alter_cards_paper'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaflets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper', models.CharField(choices=[('130', '130 г/м'), ('170', '170 г/м'), ('300', '300 г/м')], help_text='Плотность бумаги', max_length=20)),
                ('pressrun', models.IntegerField(help_text='Тираж')),
                ('duplex', models.BooleanField(choices=[(True, '4+4'), (False, '4+0')], default=True, help_text='Дуплекс')),
                ('cost', models.IntegerField(help_text='Цена', null=True)),
                ('format_choice', models.CharField(choices=[('A4', 'A4'), ('A5', 'A5'), ('A6', 'A6'), ('A7', 'A7')], default='A6', help_text='Выбор форматов', max_length=2)),
                ('x', models.IntegerField(default=105)),
                ('y', models.IntegerField(default=148)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='cards',
            name='paper',
            field=models.CharField(choices=[('300', '300 г/м')], default='300', help_text='Плотность бумаги', max_length=20),
        ),
    ]
