# Generated by Django 4.0.5 on 2023-06-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poly', '0005_alter_poly_duplex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poly',
            name='duplex',
            field=models.BooleanField(choices=[(True, 'Двухсторонняя печать'), (False, 'Односторонняя печать')], default=True, max_length=50),
        ),
    ]
