# Generated by Django 4.0.5 on 2023-06-13 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poly', '0005_remove_order_model_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_model',
            name='cost',
            field=models.IntegerField(null=True),
        ),
    ]
