# Generated by Django 4.0.5 on 2023-05-30 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poly', '0006_leaflets_alter_cards_paper'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormatsPoly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format_paper', models.CharField(max_length=5)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='leaflets',
            name='x',
            field=models.IntegerField(help_text='Горизонтальный размер'),
        ),
        migrations.AlterField(
            model_name='leaflets',
            name='y',
            field=models.IntegerField(help_text='Вертикальный размер'),
        ),
        migrations.AlterField(
            model_name='leaflets',
            name='format_choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poly.formatspoly'),
        ),
    ]
