# Generated by Django 4.0.5 on 2023-06-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poly', '0006_alter_poly_duplex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formats',
            name='format_p',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
