# Generated by Django 4.0.5 on 2023-06-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poly', '0007_alter_formats_format_p'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poly',
            name='post_obr',
            field=models.CharField(blank=True, choices=[('eurobucket', 'Евробуклет'), ('accordion', 'Гармошка'), ('book', 'Книжка')], max_length=20, null=True),
        ),
    ]
