# Generated by Django 4.0.5 on 2023-05-30 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poly', '0007_formatspoly_alter_leaflets_x_alter_leaflets_y_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaflets',
            name='x',
            field=models.IntegerField(help_text='Горизонтальный размер', null=True),
        ),
        migrations.AlterField(
            model_name='leaflets',
            name='y',
            field=models.IntegerField(help_text='Вертикальный размер', null=True),
        ),
    ]
