# Generated by Django 4.0.5 on 2023-08-04 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poly', '0008_alter_poly_post_obr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formats',
            name='x',
            field=models.IntegerField(max_length=630),
        ),
        migrations.AlterField(
            model_name='formats',
            name='y',
            field=models.IntegerField(max_length=630),
        ),
        migrations.AlterField(
            model_name='poly',
            name='format_p',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poly.formats'),
        ),
        migrations.AlterField(
            model_name='poly',
            name='pressrun',
            field=models.IntegerField(max_length=100000),
        ),
    ]
