# Generated by Django 4.0.5 on 2023-08-04 23:12

from django.db import migrations, models
import poly.models


class Migration(migrations.Migration):

    dependencies = [
        ('poly', '0009_alter_formats_x_alter_formats_y_alter_poly_format_p_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formats',
            name='x',
            field=models.IntegerField(validators=[poly.models.validate_int_size]),
        ),
        migrations.AlterField(
            model_name='formats',
            name='y',
            field=models.IntegerField(validators=[poly.models.validate_int_size]),
        ),
        migrations.AlterField(
            model_name='poly',
            name='pressrun',
            field=models.IntegerField(),
        ),
    ]
