# Generated by Django 4.0.5 on 2023-06-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poly', '0009_leaflets_model_rename_cards_card_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card_model',
            name='duplex',
            field=models.BooleanField(choices=[(True, 'Двухсторонняя печать'), (False, 'Односторонняя печать')], default=True, help_text='Дуплекс'),
        ),
        migrations.AlterField(
            model_name='card_model',
            name='paper',
            field=models.CharField(choices=[('300', '300 г/м')], help_text='Плотность бумаги', max_length=20),
        ),
        migrations.AlterField(
            model_name='leaflets_model',
            name='duplex',
            field=models.BooleanField(choices=[(True, 'Двухсторонняя печать'), (False, 'Односторонняя печать')], default=True, help_text='Дуплекс'),
        ),
    ]
