# Generated by Django 4.0.5 on 2023-06-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poly', '0010_alter_card_model_duplex_alter_card_model_paper_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formats_poly_model',
            name='format_paper',
            field=models.CharField(max_length=20),
        ),
    ]
