# Generated by Django 4.0.5 on 2023-06-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poly', '0011_alter_formats_poly_model_format_paper'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(max_length=50)),
            ],
        ),
    ]
