# Generated by Django 4.0.5 on 2023-06-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poly', '0012_order_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_model',
            name='order',
        ),
        migrations.AddField(
            model_name='card_model',
            name='type_production',
            field=models.CharField(default='card', max_length=20),
        ),
        migrations.AddField(
            model_name='leaflets_model',
            name='type_production',
            field=models.CharField(default='leaflet', max_length=20),
        ),
        migrations.AddField(
            model_name='order_model',
            name='production',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order_model',
            name='type_production',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
