# Generated by Django 4.0.5 on 2023-06-08 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poly', '0014_rename_format_choice_leaflets_model_format_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaflets_model',
            name='type_production',
        ),
    ]
