# Generated by Django 4.0.5 on 2023-06-13 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poly', '0015_remove_leaflets_model_type_production'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card_model',
            name='format',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poly.formats_poly_model'),
        ),
        migrations.AlterField(
            model_name='card_model',
            name='paper',
            field=models.CharField(choices=[('130', '130 г/м'), ('170', '170 г/м'), ('300', '300 г/м')], help_text='Плотность бумаги', max_length=20),
        ),
    ]
