# Generated by Django 4.0.5 on 2023-06-13 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poly', '0018_alter_card_model_format_alter_leaflets_model_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card_model',
            name='format',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='poly.formats_poly_model'),
        ),
        migrations.AlterField(
            model_name='leaflets_model',
            name='format',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='poly.formats_poly_model'),
        ),
    ]
