# Generated by Django 4.0.5 on 2023-08-01 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snap_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('snap_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Snap_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_stap_type', models.CharField(blank=True, max_length=30)),
                ('snap_type', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Stamp_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_stamp', models.CharField(choices=[('c_stamp', 'печать'), ('r_stamp', 'штамп')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Stamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_or_no', models.CharField(choices=[('1', 'Новая'), ('0', 'По оттиску')], default='1', max_length=30)),
                ('express', models.BooleanField(default=False)),
                ('count', models.IntegerField(default=1)),
                ('cost', models.IntegerField()),
                ('snap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='stamp.snap_item')),
                ('type_stamp', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stamp.stamp_type')),
            ],
        ),
        migrations.AddField(
            model_name='snap_item',
            name='snap_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stamp.snap_type'),
        ),
        migrations.AddField(
            model_name='snap_item',
            name='type_stamp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stamp.stamp_type'),
        ),
    ]
