# Generated by Django 4.0.5 on 2023-07-31 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stamp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stamp',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='stamp',
            name='express',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stamp',
            name='file',
            field=models.FileField(upload_to='orders'),
        ),
    ]
