# Generated by Django 4.0.5 on 2023-08-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stamp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stamp',
            name='new_or_no',
            field=models.BooleanField(choices=[(True, 'Новая'), (False, 'По оттиску')], default='new'),
        ),
    ]
