# Generated by Django 4.0.5 on 2023-08-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stamp', '0002_alter_stamp_count_alter_stamp_express_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stamp',
            name='comment',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='stamp',
            name='file',
            field=models.FileField(blank=True, upload_to='orders'),
        ),
    ]
