# Generated by Django 4.0.5 on 2023-08-04 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stamp', '0003_alter_stamp_express_alter_stamp_new_or_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snap_item',
            name='snap_img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='snap_item',
            name='snap_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stamp.snap_type'),
        ),
        migrations.AlterField(
            model_name='snap_item',
            name='type_stamp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stamp.stamp_type'),
        ),
        migrations.AlterField(
            model_name='stamp',
            name='snap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stamp.snap_item'),
        ),
        migrations.AlterField(
            model_name='stamp',
            name='type_stamp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stamp.stamp_type'),
        ),
    ]
