# Generated by Django 4.0.5 on 2023-08-01 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stamp', '0004_remove_stamp_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stamp',
            name='snap',
        ),
        migrations.AddField(
            model_name='snap_type',
            name='title_stap_type',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='stamp',
            name='snap_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='stamp.snap_type'),
        ),
        migrations.AlterField(
            model_name='snap_type',
            name='snap_type',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
