# Generated by Django 4.0.5 on 2023-08-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stamp', '0004_alter_snap_item_snap_img_alter_snap_item_snap_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stamp',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
