# Generated by Django 4.0.5 on 2023-08-01 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stamp', '0005_remove_stamp_snap_snap_type_title_stap_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stamp',
            name='snap_type',
        ),
        migrations.AddField(
            model_name='stamp',
            name='snap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='stamp.snap_item'),
        ),
        migrations.AlterField(
            model_name='snap_item',
            name='snap_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
