# Generated by Django 4.0.5 on 2023-08-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stamp', '0006_remove_stamp_snap_type_stamp_snap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stamp',
            name='new_or_no',
            field=models.CharField(choices=[('1', 'Новая'), ('0', 'По оттиску')], default='1', max_length=30),
        ),
    ]
