# Generated by Django 4.0.5 on 2023-08-01 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stamp', '0007_stamp_new_or_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stamp',
            name='comment',
        ),
    ]
